# Generated by Django 3.2.6 on 2021-09-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_auto_20210914_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='news_letter_subbed',
            field=models.BooleanField(default=False),
        ),
    ]
