# Generated by Django 3.2.6 on 2021-09-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_eventgroup_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='poster',
            field=models.ImageField(default='groupbanner.png', upload_to='group_posters'),
        ),
    ]
