# Generated by Django 3.2.6 on 2021-09-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_alter_eventgroup_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(default='poster_h9wa8t.png', upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='poster',
            field=models.ImageField(default='groupbanner_hsmr6h.png', upload_to='group_posters'),
        ),
        migrations.AlterField(
            model_name='formparent',
            name='banner_img',
            field=models.ImageField(blank=True, default='banner_iwdwal.png', null=True, upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='avatar_obrx70.png', upload_to='dp'),
        ),
    ]
