# Generated by Django 3.2.6 on 2021-10-12 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_auto_20210921_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
