# Generated by Django 3.2.6 on 2021-10-12 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_auto_20211012_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 12, 21, 31, 705833)),
        ),
    ]
